# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener-db
  template:
    metadata:
      labels:
        app: shortener-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: shortener_pg
            - name: POSTGRES_USER
              value: shortener_user
            - name: POSTGRES_PASSWORD
              value: shortener_password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name:  shortener-db-storage
      volumes:
        - name: shortener-db-storage
          emptyDir: {}
