# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shortener-db
spec:
  selector:
    app: shortener-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
